name: tetmesht
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - vtk
  - numpy
  - scipy
  - mrcfile
  - doxygen
  - pylint
  - python
  - pyopengl
  - pyrr
  - biopython
  - pip:
    - pyqt6-qt6
    - pyqt6-qt6
    - pyqt6-sip
